server:
  port: 9090

spring:
  application:
    name: microservice-order
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/OrderGoldenPearl
    username: ER_ADMIN
    password: 4686
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
