server:
  port: 8761

spring:
  application:
    name: microservice-eureka

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    eureka-server-u-r-l-context: http://localhost:${server.port}/eureka/