server:
  port: 8761

spring:
  application:
    name: microservice-eureka
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    eureka-server-u-r-l-context: http://localhost:${server.port}/eureka/